name: raffle_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_svg: ^2.2.3
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  video_player: ^2.10.1
  url_launcher: ^6.3.2
  dio: ^5.9.0
  firebase_storage: ^13.0.5
  shimmer: ^3.0.0
  cloud_firestore: ^6.1.1
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  get_it: ^9.2.0
  go_router: ^17.0.1
  multiple_result: ^5.2.0
  equatable: ^2.0.7
  another_flushbar: ^1.12.32
  percent_indicator: ^4.2.5
  flutter_markdown: ^0.7.7+1
  google_fonts: ^6.3.3
  flutter_screenutil: ^5.9.3
  chewie: ^1.13.0
  dismissible_page: ^1.0.2
  story: ^1.1.0
  mobile_scanner: ^7.1.4
  smooth_page_indicator: ^2.0.1
  google_maps_flutter: ^2.14.0
  qr_code_scanner: ^1.0.1
  flutter_card_swiper: ^7.2.0
  custom_refresh_indicator: ^4.0.1
  lottie: ^3.3.2
  camera: ^0.11.3
  inner_shadow_widget: ^0.0.3
  animated_toggle_switch: ^0.8.5
  scrollable_reorderable_navbar: ^0.0.1
  flutter_zoom_drawer: ^3.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

  
flutter_launcher_icons:  
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true
flutter_native_splash:
  image: assets/images/im_splash.png
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/gif/
    - assets/videos/
    - assets/md/


  fonts:
    - family: Noveo Sans
      fonts:
        - asset: assets/fonts/NoveoSans-Bold.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica/HelveticaNeueBold.ttf
        - asset: assets/fonts/helvetica/HelveticaNeueMedium.otf
        - asset: assets/fonts/helvetica/HelveticaNeueMedium400.otf
        - asset: assets/fonts/helvetica/Helvetica.ttf
        - asset: assets/fonts/helvetica/HelveticaNeueRoman.otf
        - asset: assets/fonts/helvetica/HelveticaNeueLight.ttf
        - asset: assets/fonts/helvetica/HelveticaNeueThin.otf
        - asset: assets/fonts/helvetica/HelveticaNeueUltraLight.otf

    - family: Galano
      fonts:
        - asset: assets/fonts/galano/GalanoGrotesqueRegular.otf
          weight: 300
        - asset: assets/fonts/galano/GalanoGrotesqueMedium.otf
          weight: 400
        - asset: assets/fonts/galano/GalanoGrotesqueMediumItalic.otf
          weight: 400
        - asset: assets/fonts/galano/GalanoGrotesqueSemiBold.otf
          weight: 500
        - asset: assets/fonts/galano/GalanoGrotesqueSemiBoldItalic.otf
          weight: 500
        - asset: assets/fonts/galano/GalanoGrotesqueBold.otf
          weight: 600
        - asset: assets/fonts/galano/GalanoGrotesqueBoldItalic.otf
          weight: 600
        - asset: assets/fonts/galano/GalanoGrotesqueExtraBold.otf
          weight: 700
        - asset: assets/fonts/galano/GalanoGrotesqueExtraBoldItalic.otf
          weight: 700

    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 300
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 400
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
          weight: 800



